from typing import Any

class PdfBitmap:
    def to_pil(self) -> Any: ...
    def close(self) -> None: ...

class PdfPage:
    def get_size(self) -> tuple[float, float]: ...
    def render(self, *, scale: float = ...) -> PdfBitmap: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, input: str) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
